CREATE TABLE CURSO (
  COD_CURSO NUMERIC(6) PRIMARY KEY NOT NULL,
  NOME_CURSO VARCHAR(50) UNIQUE NOT NULL,
  DESCRICAO_CURSO VARCHAR(300),
  VALOR NUMERIC(6, 2) NOT NULL
);

CREATE TABLE TUTOR (
  COD_TUTOR NUMERIC(6) PRIMARY KEY NOT NULL,
  NOME_TUTOR VARCHAR(50) NOT NULL,
  MATERIA_LECIONADA VARCHAR(100) NOT NULL
);

CREATE TABLE ALUNO (
  ID_ALUNO NUMERIC(7) PRIMARY KEY NOT NULL,
  NOME_ALUNO VARCHAR(110) NOT NULL,
  CPF_ALUNO VARCHAR(11) UNIQUE NOT NULL,
  DATA_NASC_ALUNO DATE,
  CURSO VARCHAR(50) NOT NULL,
  COD_TUTOR NUMERIC(6) NOT NULL,
  COMENTARIO VARCHAR(100),
  FOREIGN KEY (CURSO) REFERENCES CURSO(NOME_CURSO),
  FOREIGN KEY (COD_TUTOR) REFERENCES TUTOR(COD_TUTOR)
);


